import { AppRecord } from '../data/repository';
import { AppDefinition } from '../schema/appDefinition.schema';

export const vendorManagementAppDefinition: AppDefinition = {
  appId: 'vendor-management',
  name: 'Vendor Management',
  icon: 'package',
  version: '1.0.0',
  theme: {
    mode: 'system',
    light: {
      primaryColor: '#0f766e',
      backgroundColor: '#f8fafc',
      surfaceColor: '#ffffff',
      textColor: '#0f172a',
      mutedTextColor: '#64748b',
      borderColor: '#dbe3ea',
      successColor: '#0f766e',
      dangerColor: '#dc2626',
    },
    dark: {
      primaryColor: '#2dd4bf',
      backgroundColor: '#0b1120',
      surfaceColor: '#111827',
      textColor: '#f8fafc',
      mutedTextColor: '#94a3b8',
      borderColor: '#263244',
      successColor: '#34d399',
      dangerColor: '#f87171',
    },
    radius: 'md',
    fontScale: 1,
    fontFamily: 'system',
  },
  data: {
    storage: {
      adapter: 'sqlite',
      databaseName: 'workfoundry_templates.db',
    },
    cloudSync: {
      engine: 'supabase',
      tableName: 'ministore_records',
    },
    operations: [
      { operationId: 'vendors.list', table: 'Vendors', type: 'list' },
      { operationId: 'vendors.create', table: 'Vendors', type: 'create' },
      { operationId: 'vendors.update', table: 'Vendors', type: 'update' },
      { operationId: 'vendors.delete', table: 'Vendors', type: 'delete' },
    ],
  },
  tables: [
    {
      tableName: 'Vendors',
      fields: [
        { name: 'company_name', type: 'text', required: true },
        { name: 'contact_name', type: 'text' },
        { name: 'category', type: 'picklist', values: ['Facilities', 'Software', 'Consulting', 'Supplies', 'Marketing', 'Other'], default: 'Software' },
        { name: 'status', type: 'picklist', values: ['Active', 'Review', 'Paused', 'Offboarded'], default: 'Active' },
        { name: 'contract_value', type: 'currency', default: 0 },
        { name: 'renewal_date', type: 'date' },
        { name: 'payment_terms', type: 'picklist', values: ['Due on receipt', 'Net 15', 'Net 30', 'Net 45', 'Net 60'], default: 'Net 30' },
        { name: 'email', type: 'email' },
        { name: 'phone', type: 'phone' },
        { name: 'critical', type: 'boolean', default: false },
        { name: 'notes', type: 'textarea' },
      ],
    },
  ],
  pages: [
    {
      pageId: 'vendor_dashboard',
      title: 'Vendors',
      layout: {
        kind: 'container',
        type: 'screen',
        children: [
          {
            kind: 'container',
            type: 'stack',
            direction: 'vertical',
            children: [
              { kind: 'primitive', type: 'text', value: 'Vendors', variant: 'heading' },
              { kind: 'primitive', type: 'text', value: 'Track contracts, renewal dates, critical suppliers, and vendor spend.', variant: 'caption' },
            ],
          },
          {
            kind: 'container',
            type: 'grid',
            children: [
              {
                kind: 'widget',
                type: 'statcard',
                title: 'Vendors',
                subtitle: 'Total vendor records',
                icon: 'vendor',
                datasource: { table: 'Vendors' },
                aggregate: { fn: 'count', format: 'number' },
              },
              {
                kind: 'widget',
                type: 'statcard',
                title: 'Contract value',
                subtitle: 'Total annualized spend',
                icon: 'wallet',
                datasource: { table: 'Vendors' },
                aggregate: { field: 'contract_value', fn: 'sum', format: 'currency' },
              },
            ],
          },
          {
            kind: 'widget',
            type: 'category-breakdown',
            title: 'Spend by category',
            datasource: { table: 'Vendors' },
            categoryField: 'category',
            amountField: 'contract_value',
          },
          {
            kind: 'widget',
            type: 'timeline',
            title: 'Renewals',
            datasource: { table: 'Vendors', sort: [{ field: 'renewal_date', dir: 'asc' }] },
            dateField: 'renewal_date',
            amountField: 'contract_value',
            categoryField: 'category',
            titleField: 'company_name',
            subtitleField: 'status',
            limit: 8,
          },
          {
            kind: 'primitive',
            type: 'button',
            label: 'Add vendor',
            icon: 'plus',
            variant: 'fab',
            action: { type: 'openModal', target: 'add_vendor_modal' },
          },
        ],
      },
    },
    {
      pageId: 'vendor_list',
      title: 'Vendor Directory',
      layout: {
        kind: 'container',
        type: 'screen',
        children: [
          {
            kind: 'container',
            type: 'stack',
            direction: 'vertical',
            children: [
              { kind: 'primitive', type: 'text', value: 'Vendor directory', variant: 'heading' },
              { kind: 'primitive', type: 'text', value: 'Review contacts, terms, renewal status, and critical vendors.', variant: 'caption' },
            ],
          },
          {
            kind: 'container',
            type: 'list',
            id: 'vendor_records',
            datasource: {
              table: 'Vendors',
              sort: [{ field: 'renewal_date', dir: 'asc' }],
            },
            emptyState: {
              kind: 'primitive',
              type: 'text',
              value: 'No vendors yet. Add your first supplier.',
              variant: 'body',
            },
            itemTemplate: {
              kind: 'container',
              type: 'card',
              direction: 'horizontal',
              children: [
                {
                  kind: 'container',
                  type: 'stack',
                  direction: 'vertical',
                  children: [
                    {
                      kind: 'container',
                      type: 'stack',
                      direction: 'horizontal',
                      children: [
                        { kind: 'primitive', type: 'text', bind: 'company_name', variant: 'body' },
                        { kind: 'primitive', type: 'text', bind: 'contract_value', variant: 'body' },
                      ],
                    },
                    {
                      kind: 'container',
                      type: 'stack',
                      direction: 'horizontal',
                      children: [
                        { kind: 'primitive', type: 'badge', bind: 'status' },
                        { kind: 'primitive', type: 'badge', bind: 'category' },
                        { kind: 'primitive', type: 'text', bind: 'renewal_date', variant: 'caption' },
                      ],
                    },
                    { kind: 'primitive', type: 'text', bind: 'contact_name', variant: 'caption' },
                  ],
                },
                {
                  kind: 'primitive',
                  type: 'button',
                  label: 'Edit vendor',
                  icon: 'edit',
                  variant: 'icon',
                  action: { type: 'openModal', target: 'edit_vendor_modal', table: 'Vendors' },
                },
              ],
            },
          },
          {
            kind: 'primitive',
            type: 'button',
            label: 'Add vendor',
            icon: 'plus',
            variant: 'fab',
            action: { type: 'openModal', target: 'add_vendor_modal' },
          },
        ],
      },
    },
    {
      pageId: 'add_vendor_modal',
      title: 'New Vendor',
      layout: {
        kind: 'complex',
        type: 'modal',
        children: [
          { kind: 'primitive', type: 'input', bind: 'company_name', label: 'Company', required: true },
          { kind: 'primitive', type: 'input', bind: 'contact_name', label: 'Contact' },
          { kind: 'primitive', type: 'select', bind: 'category', label: 'Category' },
          { kind: 'primitive', type: 'select', bind: 'status', label: 'Status' },
          { kind: 'primitive', type: 'input', bind: 'contract_value', label: 'Contract value' },
          { kind: 'primitive', type: 'datepicker', bind: 'renewal_date', label: 'Renewal date' },
          { kind: 'primitive', type: 'select', bind: 'payment_terms', label: 'Payment terms' },
          { kind: 'primitive', type: 'input', bind: 'email', label: 'Email' },
          { kind: 'primitive', type: 'input', bind: 'phone', label: 'Phone' },
          {
            kind: 'container',
            type: 'stack',
            direction: 'horizontal',
            children: [
              { kind: 'primitive', type: 'checkbox', bind: 'critical' },
              { kind: 'primitive', type: 'text', value: 'Critical vendor', variant: 'body' },
            ],
          },
          { kind: 'primitive', type: 'input', bind: 'notes', label: 'Notes', multiline: true },
          {
            kind: 'primitive',
            type: 'button',
            label: 'Save',
            variant: 'filled',
            action: {
              type: 'createRecord',
              table: 'Vendors',
              onSuccess: { type: 'closeModal' },
            },
          },
        ],
      },
    },
    {
      pageId: 'edit_vendor_modal',
      title: 'Vendor Details',
      layout: {
        kind: 'complex',
        type: 'modal',
        children: [
          { kind: 'primitive', type: 'input', bind: 'company_name', label: 'Company', required: true },
          { kind: 'primitive', type: 'input', bind: 'contact_name', label: 'Contact' },
          { kind: 'primitive', type: 'select', bind: 'category', label: 'Category' },
          { kind: 'primitive', type: 'select', bind: 'status', label: 'Status' },
          { kind: 'primitive', type: 'input', bind: 'contract_value', label: 'Contract value' },
          { kind: 'primitive', type: 'datepicker', bind: 'renewal_date', label: 'Renewal date' },
          { kind: 'primitive', type: 'select', bind: 'payment_terms', label: 'Payment terms' },
          { kind: 'primitive', type: 'input', bind: 'email', label: 'Email' },
          { kind: 'primitive', type: 'input', bind: 'phone', label: 'Phone' },
          {
            kind: 'container',
            type: 'stack',
            direction: 'horizontal',
            children: [
              { kind: 'primitive', type: 'checkbox', bind: 'critical' },
              { kind: 'primitive', type: 'text', value: 'Critical vendor', variant: 'body' },
            ],
          },
          { kind: 'primitive', type: 'input', bind: 'notes', label: 'Notes', multiline: true },
          {
            kind: 'primitive',
            type: 'button',
            label: 'Save',
            variant: 'filled',
            action: {
              type: 'updateRecord',
              table: 'Vendors',
              onSuccess: { type: 'closeModal' },
            },
          },
          {
            kind: 'primitive',
            type: 'button',
            label: 'Delete vendor',
            icon: 'trash',
            variant: 'danger',
            action: {
              type: 'deleteRecord',
              table: 'Vendors',
              onSuccess: { type: 'closeModal' },
            },
          },
        ],
      },
    },
  ],
  navigation: {
    type: 'tabs',
    items: [
      { pageId: 'vendor_dashboard', label: 'Overview', icon: 'bar-chart' },
      { pageId: 'vendor_list', label: 'Vendors', icon: 'package' },
    ],
  },
};

export const vendorManagementSeedData: Record<string, AppRecord[]> = {
  Vendors: [
    {
      id: 'vendor-1',
      company_name: 'Acme Facilities',
      contact_name: 'Mira Shah',
      category: 'Facilities',
      status: 'Active',
      contract_value: 42000,
      renewal_date: '2026-10-15',
      payment_terms: 'Net 30',
      email: 'mira@acmefacilities.example',
      phone: '+1 415 555 0181',
      critical: true,
      notes: 'Primary office maintenance and repairs vendor.',
    },
    {
      id: 'vendor-2',
      company_name: 'Northstar Cloud',
      contact_name: 'Daniel Lee',
      category: 'Software',
      status: 'Review',
      contract_value: 18000,
      renewal_date: '2026-11-01',
      payment_terms: 'Net 45',
      email: 'daniel@northstarcloud.example',
      phone: '+1 212 555 0119',
      critical: true,
      notes: 'Cloud monitoring platform renewal under review.',
    },
    {
      id: 'vendor-3',
      company_name: 'Brightline Creative',
      contact_name: 'Anika Rao',
      category: 'Marketing',
      status: 'Active',
      contract_value: 12500,
      renewal_date: '2027-01-20',
      payment_terms: 'Net 15',
      email: 'anika@brightline.example',
      phone: '+1 646 555 0147',
      critical: false,
      notes: 'Campaign creative and design retainers.',
    },
    {
      id: 'vendor-4',
      company_name: 'LedgerWorks Consulting',
      contact_name: 'Owen Pierce',
      category: 'Consulting',
      status: 'Paused',
      contract_value: 9600,
      renewal_date: '2026-09-30',
      payment_terms: 'Due on receipt',
      email: 'owen@ledgerworks.example',
      phone: '+1 312 555 0174',
      critical: false,
      notes: 'Finance process review paused until Q4.',
    },
  ],
};
